Update pack

diff --git a/pack b/pack
--- a/pack
+++ b/pack
@@ -1,9 +1,16 @@
-echo "checking if $1 exists"
-if [ ! -f "$1" ]; then
+if [ ! -f "$1" ] && [ ! $1 == "-d" ]; then
     echo "finding match for $1"
     if [ $1 == "v" ]; then
         # for building v
         git clone https://github.com/vlang/v
+        cd v
+        make
+        cd ..
     else
         echo "no match found for $1 aborting"
+    fi
+fi
+# uninstaller
+if [ $1 == "-d" ]; then
+    rm -r $2 || echo "installation not found"
 fi
